spring:
  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  database:
    driverClassName: com.mysql.jdbc.Driver
  datasource:
    url: jdbc:mysql://mysql-aws.cmgnm8kwotzy.us-east-2.rds.amazonaws.com:3306/itemsharingdatabase
    username: root
    password: mysqlaws
    testWhileIdle: 'true'
    validationQuery: SELECT 1

security:
  oauth2:
    resource:
      user-info-uri: http://18.220.211.153:8901/user

server:
  port: 8901

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://18.220.211.153:8761/eureka

signing:
  key: 345345fsdgsf5345

management:
  security:
    enabled: false