spring:
  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  database:
    driverClassName: com.mysql.jdbc.Driver
  datasource:
    url: jdbc:mysql://mysql-aws.cmgnm8kwotzy.us-east-2.rds.amazonaws.com:3306/itemsharingdatabase
    username: root
    password: '{cipher}1d094d53408c2bc81fcfb7062eec889ab8fed3062bb9c2bcc591340bb4e8340c'
    testWhileIdle: 'true'
    validationQuery: SELECT 1

security:
  oauth2:
    resource:
      user-info-uri: http://18.220.211.153:8901/user

server:
  port: 8082

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://18.220.211.153:8761/eureka

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.itemsharing: DEBUG

management:
  security:
    enabled: false